### ISSUE TITLE
audio input from laptop mic

### ISSUE THREAD

**Issue by aniketmaurya** [Nachimak28/LAI-voice-search-openai-whisper-demo#3]

**Comment by Nachimak28** [comment]
Once **[this](https://github.com/gradio-app/gradio/issues/2325)** gradio issue is resolved, will make the changes. 👍

**Comment by Nachimak28** [comment]
Gradio mic issue resolved, tested on local + lit cloud and it works with correct browser permission. Closing this issue for now. 
If any errors spring up because of the mic input, please feel free to reopen this issue.
